# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-05 18:35
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0002_auto_20171105_2026'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='user_job',
            new_name='users_job',
        ),
    ]
