# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-11 17:35
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0003_auto_20171105_2035'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='users_job',
            options={'verbose_name': 'Bohdan', 'verbose_name_plural': 'Bogdanio'},
        ),
    ]
