# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-16 17:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('login', models.CharField(max_length=20)),
                ('mail', models.CharField(max_length=20)),
                ('f_name', models.CharField(max_length=20)),
                ('s_name', models.CharField(max_length=20)),
                ('time_create', models.DateTimeField(verbose_name='date registration')),
                ('status', models.BooleanField()),
            ],
        ),
    ]
